version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - yum install -y epel-release || true
      - yum update -y && yum install -y git-lfs ninja-build ccache tar gcc gcc-c++ make
      - pip install pyyaml jinja2
      - |
        echo "Installing ccache from source..."
        CCACHE_VERSION=4.6.1
        wget https://github.com/ccache/ccache/releases/download/v$CCACHE_VERSION/ccache-$CCACHE_VERSION.tar.gz
        tar -xzf ccache-$CCACHE_VERSION.tar.gz
        cd ccache-$CCACHE_VERSION
        ./configure
        make
        make install
        cd ..
        rm -rf ccache-$CCACHE_VERSION*
      - ccache --version

  pre_build:
    commands:
      - git lfs install
      - git submodule update --init --recursive
      - ccache -z

  build:
    commands:
      - mkdir build
      - cmake -B build -S .
        -GNinja
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_FLAGS=-Werror
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
        -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON 
        -DACTS_BUILD_EVERYTHING=ON
        -DACTS_BUILD_ODD=ON
        -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON
        -DACTS_BUILD_EXAMPLES_BINARIES=ON
        -DACTS_BUILD_EXAMPLES_EDM4HEP=ON
        -DACTS_FORCE_ASSERTIONS=ON
        -DACTS_BUILD_ANALYSIS_APPS=ON
        -DACTS_BUILD_PLUGIN_ONNX=ON
        -DACTS_BUILD_PLUGIN_ACTSVG=ON
      - cmake --build build
      - ccache -s

  post_build:
    commands:
      - tar czf build.tar.gz -C build --exclude "*.o" --exclude "bin/ActsUnitTest*" --exclude "bin/ActsIntegrationTest*" .

artifacts:
  files:
    - build.tar.gz

cache:
  paths:
    - '/root/.cache'
    - 'ccache'
