version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - yum install -y epel-release || true
      - yum update -y && yum install -y git-lfs ninja-build tar gcc gcc-c++ make
      - pip install pyyaml jinja2
      - curl -L https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz -o sccache.tar.gz
      - tar -xzf sccache.tar.gz
      - mv sccache-v0.2.15-x86_64-unknown-linux-musl/sccache /usr/local/bin/
      - rm -rf sccache*

  pre_build:
    commands:
      - git lfs install
      - git submodule update --init --recursive
      - sccache --start-server

  build:
    commands:
      - mkdir build
      - cmake -B build -S .
        -GNinja
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_FLAGS=-Werror
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
        -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON 
        -DACTS_BUILD_EVERYTHING=ON
        -DACTS_BUILD_ODD=ON
        -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON
        -DACTS_BUILD_EXAMPLES_BINARIES=ON
        -DACTS_BUILD_EXAMPLES_EDM4HEP=ON
        -DACTS_FORCE_ASSERTIONS=ON
        -DACTS_BUILD_ANALYSIS_APPS=ON
        -DACTS_BUILD_PLUGIN_ONNX=ON
        -DACTS_BUILD_PLUGIN_ACTSVG=ON
      - cmake --build build
      - sccache -s

  post_build:
    commands:
      - tar czf build.tar.gz -C build --exclude "*.o" --exclude "bin/ActsUnitTest*" --exclude "bin/ActsIntegrationTest*" .

artifacts:
  files:
    - build.tar.gz

cache:
  paths:
    - '/root/.cache'
    - 'sccache'
